### ISSUE TITLE
toggle enable SSL for Neptune

### ISSUE THREAD

**Issue by eerichmond** [ArcadeData/arcade-connectors#197]
I recently deployed Arcade Analytics to my Kubernetes cluster in AWS. To support AWS's V4 signing I added a proxy sidecar to my pod that captures traffic to localhost:8182 and signs the payload with AWS credentials before sending it to Neptune. Unfortunately the latest release of arcade-connector for Grelmin added code that requires `GREMLIN_NEPTUNE` type connections to have SSL enable. Adding a certificate between the Arcade Analytics Docker container and AWS v4 signing sidecar seemed like unnecessary overhead. Can the enable SSL option be turned into a user defined flag instead of hardcoded to `dataSource.type == "GREMLIN_COSMOSDB" || dataSource.type == "GREMLIN_NEPTUNE"`?
Thank you,
Eli

**Comment by arcade-player** [comment]
Ok.
Just to be sure, can you try the previous version of AA and verify that works? thanks

**Comment by arcade-player** [comment]
the latest connector release 1.0.12 of connectors, included in the ArcadeAnalysitcs 1.0.7 handles this new flag
